global_defs {
    router_id VM1
}

# Fail over if haproxy goes down on this node
vrrp_script check_haproxy {
    script "systemctl is-active --quiet haproxy"
    interval 2
    weight -30
}

vrrp_instance VI_1 {
    state MASTER
    interface enp3s0
    virtual_router_id 51
    priority 100
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass cloudvirt2026
    }

    virtual_ipaddress {
        192.168.9.110/24
    }

    track_script {
        check_haproxy
    }
}
